feed/urls.py
from django.urls import path

from . import views

app_name = "feed"

urlpatterns = [
    path("", views.HomePage.as_view(), name="index"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail" ),
    path("new/", views.CreateNewPost.as_view(), name="new_post"),
]

x/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from feed import urls as feed_urls
from profiles import urls as profiles_urls
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(feed_urls, namespace="feed")),
    path("profiles/", include(profiles_urls, namespace="profiles")),
    path("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

x/templates/includes/post.html
{% load thumbnail %}

<!-- component is from https://tailwindcomponents.com/component/post-artical -->
<div class="max-w-4xl px-10 my-4 py-6 bg-white rounded-lg shadow-md" style='width: 50rem'>
    <div class="flex justify-between items-center">
        <span class="font-light text-gray-600">{{ post.date|date:"F j, Y, g:i:a" }}</span>
        {% comment %} <a class="px-2 py-1 bg-gray-600 text-gray-100 font-bold rounded hover:bg-gray-500" href="#">Design</a> {% endcomment %}
    </div>
    <div class="mt-2">
        <p class="mt-2 text-gray-600">{{ post.text }}</p>
    </div>
    <div class="flex justify-between items-center mt-4">
        {% if show_detail_link %}
            <a class="text-blue-600 hover:underline" href="{% url 'feed:detail' post.id %}">
                Read more
            </a>
        {% else %}
            <span>&nbsp;</span>
        {% endif %}
        <div>
            <a class="flex items-center" href="{% url 'profiles:detail' post.author.username %}">
                {% thumbnail post.author.profile.image "373x372" crop="center" as im %}
                    <img class="mx-4 w-10 h-10 object-cover rounded-full hidden sm:block" src="{{ im.url }}" alt="avatar">
                {% endthumbnail %}
                <h1 class="text-gray-700 font-bold">{{ post.author.username }}</h1>
            </a>
        </div>
    </div>
</div>